[[LLD]]
arch = "aarch64"
git-tree-sha1 = "d21f52e13c9124060a32c097c4cf9170f31d8b97"
llvm_version = "20"
os = "macos"

    [[LLD.download]]
    sha256 = "d384865249ab5ca560f95d38ed628d5d2ec7c19112ec28506b0bd91e0c4bfce4"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-apple-darwin-llvm_version+20.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4e0dcd1eb3c8ca878945947ca09cacfced095aa"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "18c398b99e7c5f06fbebca4f0dad38e16a9e2fb948f351f03220746fdcfd45fc"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40e6300c6c3fbe23c6c4a07912f65aadd89e314e"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "393387e28a3f304944ffd66607c1ebd986bb39810039d62b8308ff369748591f"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "4d9dcce30d108225ac1dd159c496035da189dfd2"
llvm_version = "20"
os = "freebsd"

    [[LLD.download]]
    sha256 = "d11f1d46638c9fdafcd92a05a1654be95b6b87c289a940c0050a17bf98906751"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-unknown-freebsd-llvm_version+20.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2131cab5e2ae4bdf5ffcb0b77884d003ae4fb2d"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "8215a6bb40441e54e385de6f243d3c57faf2e3de5fd290ae2ff846178e765e2b"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f7caa8d4d72b05d54522966a401ace1dc425991"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "de149bfb81f48a331870dbf078af2fd33de86c34610dff2e2ad140eba3e1b785"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f15344677f365dfa028ef3abb9b61b74d22b65a"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "6c87a25217ee57abaaff07fcd23c10b68533ac34e12ec6f4a0c06e205bc08540"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "399048cd3ab6aa2078ef5c3cfb40966b70284d09"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "c8858fb7f6ba9976e3668c9d37d333b70390eefb13a8aecb860037ca6e93928d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "741da93fd55cb3a68653f49e51f79969d5d1332b"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "ea0d46ec3eb333f701fa3218fe8e3df17c7d7cdd939940cba5dfdbbbdc357cf5"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.i686-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c1ea5450d4683cdbb563b0ca0b7e2ec61778b11"
llvm_version = "20"
os = "windows"

    [[LLD.download]]
    sha256 = "0b05d4723591715d789d42c0cfa7f1d7175ab3125d7c1d5f5c9b15a2f35f643c"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.i686-w64-mingw32-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d72375808e4dffbb5dd5d7c16fc5223e1f3fe2b6"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "a599a7a6df6db94fac475310e48b457087c8f1991d07c3c4953fc1568ac1be07"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b535b994374a6cb681aa69e3f82c0b9bc7adec9"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "fadad68a5a7d866a977b56b652d478a3a0c993ce61794d15def4f746335e902d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.riscv64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "fceb9e7547d8cd59c089a62a542f5a9dd034ec72"
llvm_version = "20"
os = "macos"

    [[LLD.download]]
    sha256 = "e242f4edfbb3e1fa01ef4d78b756a33bb32052ee2077959286073187721b91b5"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-apple-darwin-llvm_version+20.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e19b1a4b1e72bb62b200647e117e12eb84dd939a"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "96052dfa6bfbc41930fac40b163fa47558819f7ba8ab2feed962f7e8f0743081"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e19b1a4b1e72bb62b200647e117e12eb84dd939a"
libc = "glibc"
llvm_version = "20"
os = "linux"
sanitize = "memory"

    [[LLD.download]]
    sha256 = "96052dfa6bfbc41930fac40b163fa47558819f7ba8ab2feed962f7e8f0743081"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+20.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f1010f34d48f40e5f8d7046fd0a5c2d7d7635d9"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[LLD.download]]
    sha256 = "283f0cb5bcdc4681390f105250a6c6efdeaef2b2ad8a560e507201e19267580f"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "abe76518072557efe46e3f598873ff543d9d9e3a"
llvm_version = "20"
os = "freebsd"

    [[LLD.download]]
    sha256 = "19493fdca05ee684cb09df588fb7aded838a6106ef04a60e641e735c948c5cbc"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-unknown-freebsd-llvm_version+20.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfbab741cb40b5a2ecc0eb06e8f5e7174a8e8539"
llvm_version = "20"
os = "windows"

    [[LLD.download]]
    sha256 = "56eb2e25b368561c0b3c05b3366aefa0b12d2db8c19b92a082e76f997314e8a6"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-w64-mingw32-cxx11-llvm_version+20.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "f5280429b99a136b1fbf07e1875a47fcbb1a2b4c"
llvm_version = "20.asserts"
os = "macos"

    [[LLD.download]]
    sha256 = "6a181f24bc4260ab4f75f767c0a87616f9c28a45c3f56bedb57ce3aff9eba7f1"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-apple-darwin-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79a35c8474e27ad5af735af21015d77e43e44be4"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "633acd2353c701cbe3940cad18f2c41eda51facc4f2f280f90b8aa7f7d643d0f"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13ec4f1a56edb95eefac2308ba7846c3802c640e"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "6a989b800d26c671c99bcfa8b6d4603f46dcab1a41f3b5be40a3296fcbf738fa"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "fbd614c8fdbb488f01de449ca9343582cc128dc1"
llvm_version = "20.asserts"
os = "freebsd"

    [[LLD.download]]
    sha256 = "a6b520e3b0ee950b817e24c73835bdf711c5f17a00e9c8d696745b3a4038d2e5"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.aarch64-unknown-freebsd-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c560a4ef55e5ca02de533820d2c87533b5ed4c78"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "c52bd7eaf775fb5aee6c37bae295e99abd4dc64d79117ca4505bd54b29003149"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd4019bd18ab2a98691558bb073a62133ee4cf70"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "f10ac53362f4faa43aec1a97435504671cab437be8e9e3115c4402d1f6b3a886"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1ec2c6082b9930679781c2e3973024214a08a9"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "e2cf430f8d4fa92be6e179a4575061c368b3e5c1cd5cecf9d363495c586f08ae"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a631617a07f698ff8e801d22f526dd0324787f6"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "a963919a3417310b0de4868b55dfb9caad3a3326d5700dd968c3933930d5d8d3"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fd7c267a59dd14f7ce4c99e28e0ede453ad3d8c"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "fb42e507f5e3ecc5552f1c1ce23a268ccdda32b97c60642a63643baba9d28d1d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.i686-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "251cac0bd1be7df369e7d46202e2936d94059583"
llvm_version = "20.asserts"
os = "windows"

    [[LLD.download]]
    sha256 = "ead89d51bcc6ea565299a8bfd3fec31474cbbbc0d9d98208bc7332fd1fdf187d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.i686-w64-mingw32-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12eb028ab32245478565982e37b4b5550b5dad8b"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "bbebc3a8db61549c6f9c23cc5c6a8225d9c359d19e97c26430e2c2d5bf8428de"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9cd528b8974fcb107ee9e2297072f03e535738d"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "aed02d3088dd5723f0f4a473760e1a1ce3e20e74b84ae58ac5b476fab6385d42"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.riscv64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "8892de846cb34e156cb58e984d05a253b28a97d4"
llvm_version = "20.asserts"
os = "macos"

    [[LLD.download]]
    sha256 = "963589d3117d8480a533b826f8a71e31da18068b884fdf1f81d2ad416c441bcf"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-apple-darwin-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65fb9e0c03eb3e4f804a782a77cd73bdf35d89a3"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "866dded04d20d55cf008f3fd7e1c7bd4b6355770fa6437538b1d1f57d7bafdc7"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65fb9e0c03eb3e4f804a782a77cd73bdf35d89a3"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"
sanitize = "memory"

    [[LLD.download]]
    sha256 = "866dded04d20d55cf008f3fd7e1c7bd4b6355770fa6437538b1d1f57d7bafdc7"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "776a3d1c34a8b3d19856c93dd56ae21213707da8"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "ee0d135e98391121481d6db341844f959244c6c78f34a4e87357ac8507bcc54b"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "2fcaa0ae986746bdecb26140a76a2c7afe8b289e"
llvm_version = "20.asserts"
os = "freebsd"

    [[LLD.download]]
    sha256 = "d6f7ee81d97a0f7320a5844e42708f238e0d8d0f2f61c4a81405dd8349450d2a"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-unknown-freebsd-llvm_version+20.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5245acdbe8429f4f01ca5034a95196444fc4ed2c"
llvm_version = "20.asserts"
os = "windows"

    [[LLD.download]]
    sha256 = "be386041c826aa852cc88f4400456f7c488c3a29b376958d932f02aad4d2bcba"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v20.1.8+2/LLD.v20.1.8.x86_64-w64-mingw32-cxx11-llvm_version+20.asserts.tar.gz"
