[[LLD]]
arch = "aarch64"
git-tree-sha1 = "5adb0b2bd154162892d7269c8e550340f291586e"
llvm_version = "23"
os = "macos"

    [[LLD.download]]
    sha256 = "977b26faf1cf15617aa263c6827e810e1acf0169d89d668a46fcfb9d9ee10371"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-apple-darwin-llvm_version+23.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2762a906be832b70506d6378db8e70e15b6c52f"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "c85a3fbf28352b48b2cfd0595227ccb2c43f696ec17365146a6465cf35030456"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d1492f40104eb36d09e4666af6b9cc98c9e916b"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "3dcd69b8793fe19be6220e191b5b521ddf06da02d29cf62660b3274a150d3115"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-linux-musl-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "f4cc9bc3ce4f4a0b46270a48c56a983b8ce5d773"
llvm_version = "23"
os = "freebsd"

    [[LLD.download]]
    sha256 = "b879d9dfd35b1a2a1ecd10847a748b1e6e6698dd754226141767f1dc2fe93f8b"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-unknown-freebsd-llvm_version+23.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "462afc839916edfce91946b6d69d112c458caec8"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "070b0943ff0849785254bdc14ba0ce5d76279db6c3e0d20362c12222adb28ebc"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv6l-linux-gnueabihf-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4506ae9ee0eb8e060e6668e37b8dd2514330a5c7"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "7911850e480582b951ac4b53f12a025a2acafb6c03bf543ea204b0263508cde8"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv6l-linux-musleabihf-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a60186a10bfe9c68b5f4ab551e8e72eb89c9fb54"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "9a03ba69ea973e7837e9c0c354d33ce045bde0ef93792d5b991aa27542edee91"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv7l-linux-gnueabihf-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91885669830a8a3717afe73d59d0bc4782ed0581"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "9279a668abed2be75e944f6da5d3dfe4a3ec7e7754853c4665ec3a3ed044a7ab"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv7l-linux-musleabihf-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7205469aecdec63ce83e9f0d60a62e6f442f5098"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "20bd3e7749bde19e79a3a187213e60615a2f1dac08a2a15e3b690fdfca1f8ab9"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.i686-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95481aaa2688eefdc25d307ca67c56a82a94745a"
llvm_version = "23"
os = "windows"

    [[LLD.download]]
    sha256 = "b950740dd073cb481fba978b1c18fe1f29e7f22958784988bfc2e7fcf3b586ea"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.i686-w64-mingw32-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd0c635e98fed178c29beea6fed207079b95e179"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "947804803083dfc348bb3432396878b22eafc2ae69847d0d5d3cab49c283753a"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.powerpc64le-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41745901188b3d3d66e24d02f09e297436eb886a"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "641571b64f3008d5e8e4e9915f673413c099b8fccb25bc647ef6edee5da5aca3"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.riscv64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "030164586ebeb9675a1019c736161d1859a0b9d1"
llvm_version = "23"
os = "macos"

    [[LLD.download]]
    sha256 = "802385a8b2d27afd2157a8467c6c9e3bef8b8dc02106261ff53613367079aba1"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-apple-darwin-llvm_version+23.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b942330e2fe2a8990ba1186c8b611e3657078841"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "8a7eb792ec062ad11d4c65d403668b1292168f8bb9a02e5f55723aeb48b74538"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b942330e2fe2a8990ba1186c8b611e3657078841"
libc = "glibc"
llvm_version = "23"
os = "linux"
sanitize = "memory"

    [[LLD.download]]
    sha256 = "8a7eb792ec062ad11d4c65d403668b1292168f8bb9a02e5f55723aeb48b74538"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+23.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72570027f557797123a72a7d1d9f2a9c5b04f89c"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[LLD.download]]
    sha256 = "88d0ee665af555f928e5a6afae67fec450d8fd1e80ec0cc28363413f1c965bab"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-linux-musl-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "69b9aa7a4e4191b9a9df50fb1be4b13ebfdcc471"
llvm_version = "23"
os = "freebsd"

    [[LLD.download]]
    sha256 = "b57315539551d812c2f009cd28bd26d5c7126fca8cd89fa834f800c8032990aa"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-unknown-freebsd-llvm_version+23.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8244667302d080ac3ed15bf02f29be910e0ca7d"
llvm_version = "23"
os = "windows"

    [[LLD.download]]
    sha256 = "d53d49739d8e4c12936b8a341a097e9be5d94e813b0cb8f96cf1816d509747e9"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-w64-mingw32-cxx11-llvm_version+23.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "556dd617bdaee643cd582fdee10a6ab221640650"
llvm_version = "23.asserts"
os = "macos"

    [[LLD.download]]
    sha256 = "815c84ba910ce3446409a4f67fa310c8e6175cd63e7ed3661dc2a63edc8f5f64"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-apple-darwin-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddb28a44b62f0fbc8edc57a13fab9138bc6d3093"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "66bb7c3e40cbc7973031928b89e0757a55c880e37e2b1877ded980e5c3969217"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce9353a0735ebd21eacbafd3b909577796c309bc"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "3b45d51c3b2dcf14a7cd8e351106dcd54c80540d1ccb5d56196f90d161a50621"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-linux-musl-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "357bca04ca17e7d80c252e592da7166259aab0ab"
llvm_version = "23.asserts"
os = "freebsd"

    [[LLD.download]]
    sha256 = "b1041c5f1e1be166ecd5cd2198cc36bee7f987d82889fab2b0a8de9ff6f1c047"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.aarch64-unknown-freebsd-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76439b40edbb526c4c0442f425b493f6fbea437a"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "4b691343540184a97811f6ac4c897c8b11ab7553f44d0539f71f092ef22fc397"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv6l-linux-gnueabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a310ce29814a9363dd1302284bf7959cc690abab"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "65f06bc39d95e5447e2be599e5800dc55f5abbaf81f75b1c8d2a5cbd866c526e"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv6l-linux-musleabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "103f317929975f0267616640d15db09fa4d91cc0"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "634876276364dfd9bce4da90a3141c21ff674061d8ee8d79296e7b57ad6075bc"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv7l-linux-gnueabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e340595ba52fb301b1063c5c96737e9355ec580"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "1772413cf66c7ef7261fc0a50d1b9b642ba29e9595249b6617717e68ccfa36e6"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.armv7l-linux-musleabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2a422c7907145112febad745884e7edcf3537c4"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "6af1cc0a9822e3696e5161b9d142b947dc25664075e3c0f278f34ee3b9545fe2"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.i686-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4be580cb3cffbaaa002e6f08a9eb5c0257aea27"
llvm_version = "23.asserts"
os = "windows"

    [[LLD.download]]
    sha256 = "a0cbd34abf23ffa95f0f58d353cae8db0b21b0882ac81739a53d03107dee7623"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.i686-w64-mingw32-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa3efae64395fc08d7311458557c24811ccb8110"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "9d607ac841cef39dd35b87a01393fbfb0f23735abc7dc9edcd065dde033fb610"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.powerpc64le-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0e31842837c9985e4b6bd0053a5a8c02e9f865a"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "9057338c3b839b075eeb012d02903e13097fa1e1d665c3340182a845e6eba880"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.riscv64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "1a83968ae284ac2b89a6455285041fc7867c5ba3"
llvm_version = "23.asserts"
os = "macos"

    [[LLD.download]]
    sha256 = "6fe41195571b96926df4c8b9d23e416dff2d75fb676430a2722d00e5500c380a"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-apple-darwin-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d18b6f110afd213ad7f517f2dea110df2808937"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "f279e5502c6bd09b5a3481b103b4b397677d79977882f178d80568d1bd00ed1d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d18b6f110afd213ad7f517f2dea110df2808937"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"
sanitize = "memory"

    [[LLD.download]]
    sha256 = "f279e5502c6bd09b5a3481b103b4b397677d79977882f178d80568d1bd00ed1d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1e37d41bea8b13227f15f7951c3ea128c53df62"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "2e669887f5ab0b6f18daf30001552d3566d39018510e90b2feedc1d49c980999"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-linux-musl-cxx11-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "506e6b592284f23299fae14071f7397e0df96e75"
llvm_version = "23.asserts"
os = "freebsd"

    [[LLD.download]]
    sha256 = "80ddf46fbb8aece44ac9e21712c1d5ad5931534c9deabc0f58931a29f9f22d76"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-unknown-freebsd-llvm_version+23.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f13d7dcda550ed9dd88fe7c22c24746ab2ac39b9"
llvm_version = "23.asserts"
os = "windows"

    [[LLD.download]]
    sha256 = "d0d43da55c39298e98a3ab32e23bd19f55894de97ce5dce58a6de9643d7b700b"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v23.1.1+0/LLD.v23.1.1.x86_64-w64-mingw32-cxx11-llvm_version+23.asserts.tar.gz"
