[[LLD]]
arch = "aarch64"
git-tree-sha1 = "e3bc56a75c00e8e2430ceb044049c68b355f28ee"
llvm_version = "21"
os = "macos"

    [[LLD.download]]
    sha256 = "6ff94848266686df2516e003e30bfabf7cd1186b370d58432a4d87f48e6b1bd9"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-apple-darwin-llvm_version+21.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d1e694938657b865f6ba5bfd7d9c255743c12d6"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "35d6c408a842e800dc9541189ff95c4700de27d8c0c5cce3739c60f4a94789e5"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c73b6651370ee41176967fba1642b8261f2dee51"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "9ab04f0bb99701e9f94ee4451526afb4cad4ab269ef156ac6fcc48a4525c0043"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-linux-musl-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "ed00dbe7b4f8b2734b6b341c45aaf109cfe06487"
llvm_version = "21"
os = "freebsd"

    [[LLD.download]]
    sha256 = "30d438e811d13400c7b26cfef81de26c318c55d0911cdd3dae597b81e8dcfee5"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-unknown-freebsd-llvm_version+21.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1017d3259196cf10eb78b88cf385304bc1fe5a77"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "17f415b6b570a9798d4dd1c3bf02d0383a73a31ed91a6ed2f3ded2f72b9a6e2d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8def6ad9eac4182598ec5cd243757cb634b07cf"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "d5159503580089df15330df4e71ecf3b30e2908c659d151a17d0db8da5481423"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e4d33ea597b5e3c8079b75a52d9850fa4adbe64"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "88d2b854364d9683c4ffc315878b04a56b44fce50252b6adda93ea69c635ebd9"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14a525f4ce1e04cbf2f6b23941908d2a47dc2466"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "5c555258a4c29c78e77b5e811dad78573b2993c9280d834491f1d3f4a486c926"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e12084b07fa59acf91300a564a6b0fe3001defb"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "cfb5b89f83f3d1bb21577c0e6c6a5a90bba1fb74fcd491a5283b7f6eb09c6fa6"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.i686-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09dba1c77532540e5c978a0f675ffea3696bfec0"
llvm_version = "21"
os = "windows"

    [[LLD.download]]
    sha256 = "05a4c295694e91f2ecbd5a09109d65e4bdbe72eaffa62d3720e1bb833eaa1520"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.i686-w64-mingw32-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24023da4a259703272f9812e9f54ad80c285782f"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "20efcb31702b6424f633926c6ecaea8d64da762231ad97270620f53320cf7e79"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55a168f069efd276c39b9cdf92c1f8b284496982"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "7bd82b1da70f1305e8102cbebcb9001f866d7d93e5d02bbf86c7ba8506ab1368"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.riscv64-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "64d7b16048f181d6c18327cbb43713f5df1f4a20"
llvm_version = "21"
os = "macos"

    [[LLD.download]]
    sha256 = "493b1bbb448449e462650c5d19edb0cbd9607a46a03f396bc8514770f35a255f"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-apple-darwin-llvm_version+21.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c4d6cdc9f5934c381882ea8f634dece16723c19"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "b8781646e60477de3ef2d236e4ebd8ff5db363353ed3a6522b5676624cab11f0"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c4d6cdc9f5934c381882ea8f634dece16723c19"
libc = "glibc"
llvm_version = "21"
os = "linux"
sanitize = "memory"

    [[LLD.download]]
    sha256 = "b8781646e60477de3ef2d236e4ebd8ff5db363353ed3a6522b5676624cab11f0"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+21.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02b15276b8142c2c85a87e2752f15ad8f063cca4"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[LLD.download]]
    sha256 = "0b7b2c16a98e689e8f65ad6b0ea940d724c9314836782046ef29a7a46207896d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-linux-musl-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "c626bb12d1d45d273673a233b8ec52c6ba85648b"
llvm_version = "21"
os = "freebsd"

    [[LLD.download]]
    sha256 = "9a7ef9b74d2055de373802a254a46aab629db71533974ff2470d6d7ef43ca8e3"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-unknown-freebsd-llvm_version+21.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94a285ab5f76b868d0c6b321686de0e6bd7f4010"
llvm_version = "21"
os = "windows"

    [[LLD.download]]
    sha256 = "466b3e3a61b6ac3acdeee701f5dc4e59fecbc03611570461d46a2dd0d3c8166e"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-w64-mingw32-cxx11-llvm_version+21.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "6a5375a1ee285a20e80eacc7ffa7fbe6aa647315"
llvm_version = "21.asserts"
os = "macos"

    [[LLD.download]]
    sha256 = "8e6f505b9de61cb9171e9988eea055ff1d42e7cf7fa7a571325f0ff82c8850db"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-apple-darwin-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8a5e2567f651b6f56738351263b1e6d44012339"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "fbe0e6a22a48d5bbd3d1a257d455705ae9744ed06b6c70b7f969a4641535865d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f0db2671dfe9a8d2a2078645842ef296b012ba5"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "69853759d7ca29256262c569b27b1fd6547c67a22062f3faa01396ba327401c2"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-linux-musl-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "aarch64"
git-tree-sha1 = "054fad4f9e48e5454e70fddf9cccf38989bd7429"
llvm_version = "21.asserts"
os = "freebsd"

    [[LLD.download]]
    sha256 = "10eb9e29453db8988e5dc2b40f6a94dce303a6715db4326b5291f9ed02811b6a"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.aarch64-unknown-freebsd-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b99792d391e846d5d807eae58b63690cb0363eee"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "ab992aa2b39992a51c14ef4522b896645cabe50c129e1da534703f7503d43460"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06cff8d5b062e62c82d2045891ac8050d72ed862"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "85e1769c939c041e327876ee379b36add9fa573d521a4572ac2d40606d3c368e"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "842cb8f05976911e908278b8f12ca4e9bd431772"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "f6d70a46b76a7ad85fd27d807e4e2a99b9cc8115e4ea7f756e4bf3ef45b357c9"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e691da99ed65ee0f4580e537bc1cb4734d772123"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "f41be220dcf725e4ca376c56a8496059323d098c5bc60171304edbc5b343ad29"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a103f5129fbf384544fe4e5395b3a8b003ea28ef"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "a193269b985df41bf0d668a760cbb1e0e4efebcbf0a66c07a23b7a24bb6d9a27"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.i686-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42f221cbe5bd85b8281555607b53d1599ed2d205"
llvm_version = "21.asserts"
os = "windows"

    [[LLD.download]]
    sha256 = "6652c9e081d80c8735108306ec090398b32670ac5a79df204b409a6d985b66ad"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.i686-w64-mingw32-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc7827dbe693d41cb0fe15029c0410bdfd2b21c7"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "324cf1b0b751c1ac99967b018019166b07947a530c77830310b3ad8bb9d1a0ac"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35b8765f1fbc4dcf6f3fbb07f7c0975e6af2ef1b"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "35a24d059711a87b709f2f82d842dfc0cb537ad4818e9a483df25bee69cd7753"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.riscv64-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "bb50b89df81d50f6f0fabf853a975326196143dc"
llvm_version = "21.asserts"
os = "macos"

    [[LLD.download]]
    sha256 = "3fe534c95f5ef532db911197087307e8bad0507a965f7847d291ba3fb241c145"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-apple-darwin-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "159eba4e7c1ac151648bbd6c608b24d37f7b411d"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "0eb5c08046cd0be5a27dcd53637ec63787359eb08f6f47ce9710d616f12e3c6d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "159eba4e7c1ac151648bbd6c608b24d37f7b411d"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"
sanitize = "memory"

    [[LLD.download]]
    sha256 = "0eb5c08046cd0be5a27dcd53637ec63787359eb08f6f47ce9710d616f12e3c6d"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe4e6e529db21d3ae0fb17be3fcb45d45db186b9"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[LLD.download]]
    sha256 = "57c9dc7478c38b6fe9a24b9aa821cda370b5a3fbaaee42abcf0fc23a9c776bd0"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-linux-musl-cxx11-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
git-tree-sha1 = "e46799519b70f7f31207d11d79c645caf6cfec8c"
llvm_version = "21.asserts"
os = "freebsd"

    [[LLD.download]]
    sha256 = "12b9281b4abb7b8c7b06d4b77cafea32617980597f134424cbf2b93476aabc69"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-unknown-freebsd-llvm_version+21.asserts.tar.gz"
[[LLD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ffa0709612c98c2fd938d8be94e136d8b5fac43"
llvm_version = "21.asserts"
os = "windows"

    [[LLD.download]]
    sha256 = "f0b90d1228ef1580e16714940ad233c184ce4b8c2dcfab424a0ba88203e18d89"
    url = "https://github.com/JuliaBinaryWrappers/LLD_jll.jl/releases/download/LLD-v21.1.8+2/LLD.v21.1.8.x86_64-w64-mingw32-cxx11-llvm_version+21.asserts.tar.gz"
